# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'game.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLCDNumber, QLabel,
    QLayout, QPushButton, QSizePolicy, QSpacerItem,
    QVBoxLayout, QWidget)
import Icons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1320, 1277)
        font = QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout_3 = QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetFixedSize)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetMaximumSize)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.boardImageLabel = QLabel(self.groupBox)
        self.boardImageLabel.setObjectName(u"boardImageLabel")
        self.boardImageLabel.setGeometry(QRect(0, 0, 1151, 1161))
        self.endTurnButton = QPushButton(self.groupBox)
        self.endTurnButton.setObjectName(u"endTurnButton")
        self.endTurnButton.setGeometry(QRect(330, 540, 231, 121))
        font1 = QFont()
        font1.setPointSize(24)
        self.endTurnButton.setFont(font1)
        self.bankruptButton = QPushButton(self.groupBox)
        self.bankruptButton.setObjectName(u"bankruptButton")
        self.bankruptButton.setGeometry(QRect(610, 540, 221, 121))
        self.bankruptButton.setFont(font1)
        self.displayLabel = QLabel(self.groupBox)
        self.displayLabel.setObjectName(u"displayLabel")
        self.displayLabel.setGeometry(QRect(210, 880, 731, 71))
        self.displayLabel.setAlignment(Qt.AlignCenter)
        self.displayLabel.setWordWrap(True)
        self.dice1Outline = QLabel(self.groupBox)
        self.dice1Outline.setObjectName(u"dice1Outline")
        self.dice1Outline.setGeometry(QRect(380, 690, 161, 161))
        self.dice1Outline.setFrameShape(QFrame.Box)
        self.dice2Outline = QLabel(self.groupBox)
        self.dice2Outline.setObjectName(u"dice2Outline")
        self.dice2Outline.setGeometry(QRect(630, 690, 161, 161))
        self.dice2Outline.setFrameShape(QFrame.Box)
        self.dice1dot1 = QLabel(self.groupBox)
        self.dice1dot1.setObjectName(u"dice1dot1")
        self.dice1dot1.setGeometry(QRect(390, 670, 41, 91))
        font2 = QFont()
        font2.setPointSize(50)
        self.dice1dot1.setFont(font2)
        self.dice1dot4 = QLabel(self.groupBox)
        self.dice1dot4.setObjectName(u"dice1dot4")
        self.dice1dot4.setGeometry(QRect(440, 720, 41, 91))
        self.dice1dot4.setFont(font2)
        self.dice1dot6 = QLabel(self.groupBox)
        self.dice1dot6.setObjectName(u"dice1dot6")
        self.dice1dot6.setGeometry(QRect(390, 770, 41, 91))
        self.dice1dot6.setFont(font2)
        self.dice1dot7 = QLabel(self.groupBox)
        self.dice1dot7.setObjectName(u"dice1dot7")
        self.dice1dot7.setGeometry(QRect(490, 770, 41, 91))
        self.dice1dot7.setFont(font2)
        self.dice1dot2 = QLabel(self.groupBox)
        self.dice1dot2.setObjectName(u"dice1dot2")
        self.dice1dot2.setGeometry(QRect(490, 670, 41, 91))
        self.dice1dot2.setFont(font2)
        self.dice1dot5 = QLabel(self.groupBox)
        self.dice1dot5.setObjectName(u"dice1dot5")
        self.dice1dot5.setGeometry(QRect(490, 720, 41, 91))
        self.dice1dot5.setFont(font2)
        self.dice1dot3 = QLabel(self.groupBox)
        self.dice1dot3.setObjectName(u"dice1dot3")
        self.dice1dot3.setGeometry(QRect(390, 720, 41, 91))
        self.dice1dot3.setFont(font2)
        self.dice2dot5 = QLabel(self.groupBox)
        self.dice2dot5.setObjectName(u"dice2dot5")
        self.dice2dot5.setGeometry(QRect(740, 720, 41, 91))
        self.dice2dot5.setFont(font2)
        self.dice2dot3 = QLabel(self.groupBox)
        self.dice2dot3.setObjectName(u"dice2dot3")
        self.dice2dot3.setGeometry(QRect(640, 720, 41, 91))
        self.dice2dot3.setFont(font2)
        self.dice2dot7 = QLabel(self.groupBox)
        self.dice2dot7.setObjectName(u"dice2dot7")
        self.dice2dot7.setGeometry(QRect(740, 770, 41, 91))
        self.dice2dot7.setFont(font2)
        self.dice2dot6 = QLabel(self.groupBox)
        self.dice2dot6.setObjectName(u"dice2dot6")
        self.dice2dot6.setGeometry(QRect(640, 770, 41, 91))
        self.dice2dot6.setFont(font2)
        self.dice2dot1 = QLabel(self.groupBox)
        self.dice2dot1.setObjectName(u"dice2dot1")
        self.dice2dot1.setGeometry(QRect(640, 670, 41, 91))
        self.dice2dot1.setFont(font2)
        self.dice2dot2 = QLabel(self.groupBox)
        self.dice2dot2.setObjectName(u"dice2dot2")
        self.dice2dot2.setGeometry(QRect(740, 670, 41, 91))
        self.dice2dot2.setFont(font2)
        self.dice2dot4 = QLabel(self.groupBox)
        self.dice2dot4.setObjectName(u"dice2dot4")
        self.dice2dot4.setGeometry(QRect(690, 720, 41, 91))
        self.dice2dot4.setFont(font2)
        self.lcdNumber = QLCDNumber(self.groupBox)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(941, 970, 20, 31))
        self.lcdNumber.setFrameShape(QFrame.NoFrame)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_2 = QLCDNumber(self.groupBox)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(770, 970, 20, 31))
        self.lcdNumber_2.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_2.setDigitCount(1)
        self.lcdNumber_2.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_3 = QLCDNumber(self.groupBox)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(510, 970, 20, 31))
        self.lcdNumber_3.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_3.setDigitCount(1)
        self.lcdNumber_3.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_4 = QLCDNumber(self.groupBox)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(340, 970, 20, 31))
        self.lcdNumber_4.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_4.setDigitCount(1)
        self.lcdNumber_4.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_5 = QLCDNumber(self.groupBox)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(260, 970, 20, 31))
        self.lcdNumber_5.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_5.setDigitCount(1)
        self.lcdNumber_5.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_6 = QLCDNumber(self.groupBox)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(170, 930, 21, 31))
        self.lcdNumber_6.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_6.setDigitCount(1)
        self.lcdNumber_6.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_7 = QLCDNumber(self.groupBox)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(170, 770, 21, 31))
        self.lcdNumber_7.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_7.setDigitCount(1)
        self.lcdNumber_7.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_8 = QLCDNumber(self.groupBox)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(170, 680, 21, 31))
        self.lcdNumber_8.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_8.setDigitCount(1)
        self.lcdNumber_8.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_9 = QLCDNumber(self.groupBox)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(170, 510, 21, 31))
        self.lcdNumber_9.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_9.setDigitCount(1)
        self.lcdNumber_9.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_10 = QLCDNumber(self.groupBox)
        self.lcdNumber_10.setObjectName(u"lcdNumber_10")
        self.lcdNumber_10.setGeometry(QRect(170, 340, 21, 31))
        self.lcdNumber_10.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_10.setDigitCount(1)
        self.lcdNumber_10.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_11 = QLCDNumber(self.groupBox)
        self.lcdNumber_11.setObjectName(u"lcdNumber_11")
        self.lcdNumber_11.setGeometry(QRect(170, 250, 21, 31))
        self.lcdNumber_11.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_11.setDigitCount(1)
        self.lcdNumber_11.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_12 = QLCDNumber(self.groupBox)
        self.lcdNumber_12.setObjectName(u"lcdNumber_12")
        self.lcdNumber_12.setGeometry(QRect(200, 170, 21, 31))
        self.lcdNumber_12.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_12.setDigitCount(1)
        self.lcdNumber_12.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_13 = QLCDNumber(self.groupBox)
        self.lcdNumber_13.setObjectName(u"lcdNumber_13")
        self.lcdNumber_13.setGeometry(QRect(370, 170, 21, 31))
        self.lcdNumber_13.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_13.setDigitCount(1)
        self.lcdNumber_13.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_14 = QLCDNumber(self.groupBox)
        self.lcdNumber_14.setObjectName(u"lcdNumber_14")
        self.lcdNumber_14.setGeometry(QRect(460, 170, 21, 31))
        self.lcdNumber_14.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_14.setDigitCount(1)
        self.lcdNumber_14.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_15 = QLCDNumber(self.groupBox)
        self.lcdNumber_15.setObjectName(u"lcdNumber_15")
        self.lcdNumber_15.setGeometry(QRect(630, 170, 21, 31))
        self.lcdNumber_15.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_15.setDigitCount(1)
        self.lcdNumber_15.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_16 = QLCDNumber(self.groupBox)
        self.lcdNumber_16.setObjectName(u"lcdNumber_16")
        self.lcdNumber_16.setGeometry(QRect(710, 170, 21, 31))
        self.lcdNumber_16.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_16.setDigitCount(1)
        self.lcdNumber_16.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_17 = QLCDNumber(self.groupBox)
        self.lcdNumber_17.setObjectName(u"lcdNumber_17")
        self.lcdNumber_17.setGeometry(QRect(880, 170, 21, 31))
        self.lcdNumber_17.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_17.setDigitCount(1)
        self.lcdNumber_17.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_18 = QLCDNumber(self.groupBox)
        self.lcdNumber_18.setObjectName(u"lcdNumber_18")
        self.lcdNumber_18.setGeometry(QRect(970, 200, 21, 31))
        self.lcdNumber_18.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_18.setDigitCount(1)
        self.lcdNumber_18.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_19 = QLCDNumber(self.groupBox)
        self.lcdNumber_19.setObjectName(u"lcdNumber_19")
        self.lcdNumber_19.setGeometry(QRect(970, 290, 21, 31))
        self.lcdNumber_19.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_19.setDigitCount(1)
        self.lcdNumber_19.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_20 = QLCDNumber(self.groupBox)
        self.lcdNumber_20.setObjectName(u"lcdNumber_20")
        self.lcdNumber_20.setGeometry(QRect(970, 460, 21, 31))
        self.lcdNumber_20.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_20.setDigitCount(1)
        self.lcdNumber_20.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_21 = QLCDNumber(self.groupBox)
        self.lcdNumber_21.setObjectName(u"lcdNumber_21")
        self.lcdNumber_21.setGeometry(QRect(970, 720, 21, 31))
        self.lcdNumber_21.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_21.setDigitCount(1)
        self.lcdNumber_21.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_22 = QLCDNumber(self.groupBox)
        self.lcdNumber_22.setObjectName(u"lcdNumber_22")
        self.lcdNumber_22.setGeometry(QRect(970, 890, 21, 31))
        self.lcdNumber_22.setFrameShape(QFrame.NoFrame)
        self.lcdNumber_22.setDigitCount(1)
        self.lcdNumber_22.setSegmentStyle(QLCDNumber.Filled)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(910, 970, 20, 21))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label.setPalette(palette)
        font3 = QFont()
        font3.setPointSize(25)
        self.label.setFont(font3)
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(740, 970, 20, 21))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_2.setPalette(palette1)
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(490, 970, 20, 21))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_3.setPalette(palette2)
        self.label_3.setFont(font3)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(320, 970, 20, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_4.setPalette(palette3)
        self.label_4.setFont(font3)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 970, 20, 21))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_5.setPalette(palette4)
        self.label_5.setFont(font3)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 910, 20, 21))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_6.setPalette(palette5)
        self.label_6.setFont(font3)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(170, 750, 20, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_7.setPalette(palette6)
        self.label_7.setFont(font3)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(170, 660, 20, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_8.setPalette(palette7)
        self.label_8.setFont(font3)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(170, 490, 20, 21))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_9.setPalette(palette8)
        self.label_9.setFont(font3)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 320, 20, 21))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_10.setPalette(palette9)
        self.label_10.setFont(font3)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(170, 230, 20, 21))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_11.setPalette(palette10)
        self.label_11.setFont(font3)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(220, 170, 20, 21))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_12.setPalette(palette11)
        self.label_12.setFont(font3)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 170, 20, 21))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_13.setPalette(palette12)
        self.label_13.setFont(font3)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(480, 170, 20, 21))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_14.setPalette(palette13)
        self.label_14.setFont(font3)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(650, 170, 20, 21))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_15.setPalette(palette14)
        self.label_15.setFont(font3)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(730, 170, 20, 21))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_16.setPalette(palette15)
        self.label_16.setFont(font3)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(900, 170, 20, 21))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_17.setPalette(palette16)
        self.label_17.setFont(font3)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(970, 230, 20, 21))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_18.setPalette(palette17)
        self.label_18.setFont(font3)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(970, 320, 20, 21))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_19.setPalette(palette18)
        self.label_19.setFont(font3)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(970, 490, 20, 21))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_20.setPalette(palette19)
        self.label_20.setFont(font3)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(970, 750, 20, 21))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_21.setPalette(palette20)
        self.label_21.setFont(font3)
        self.label_21.setFrameShape(QFrame.NoFrame)
        self.label_21.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(970, 920, 20, 21))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_22.setPalette(palette21)
        self.label_22.setFont(font3)
        self.label_22.setFrameShape(QFrame.NoFrame)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.groupBox)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(570, 970, 20, 21))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_23.setPalette(palette22)
        self.label_23.setFont(font3)
        self.label_23.setFrameShape(QFrame.NoFrame)
        self.label_23.setAlignment(Qt.AlignCenter)
        self.label_24 = QLabel(self.groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(170, 820, 20, 21))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_24.setPalette(palette23)
        self.label_24.setFont(font3)
        self.label_24.setFrameShape(QFrame.NoFrame)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_25 = QLabel(self.groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(170, 580, 20, 21))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_25.setPalette(palette24)
        self.label_25.setFont(font3)
        self.label_25.setFrameShape(QFrame.NoFrame)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(self.groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(570, 170, 20, 21))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_26.setPalette(palette25)
        self.label_26.setFont(font3)
        self.label_26.setFrameShape(QFrame.NoFrame)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_27 = QLabel(self.groupBox)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(830, 170, 20, 21))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_27.setPalette(palette26)
        self.label_27.setFont(font3)
        self.label_27.setFrameShape(QFrame.NoFrame)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(self.groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(970, 570, 20, 21))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_28.setPalette(palette27)
        self.label_28.setFont(font3)
        self.label_28.setFrameShape(QFrame.NoFrame)
        self.label_28.setAlignment(Qt.AlignCenter)
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(890, 970, 21, 31))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        self.label_29.setFont(font4)
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(710, 970, 21, 31))
        self.label_30.setFont(font4)
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(540, 970, 21, 31))
        self.label_31.setFont(font4)
        self.label_32 = QLabel(self.groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(460, 970, 21, 31))
        self.label_32.setFont(font4)
        self.label_33 = QLabel(self.groupBox)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(290, 970, 21, 31))
        self.label_33.setFont(font4)
        self.label_34 = QLabel(self.groupBox)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(200, 970, 21, 31))
        self.label_34.setFont(font4)
        self.label_35 = QLabel(self.groupBox)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(170, 880, 21, 31))
        self.label_35.setFont(font4)
        self.label_36 = QLabel(self.groupBox)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(170, 720, 21, 31))
        self.label_36.setFont(font4)
        self.label_37 = QLabel(self.groupBox)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(170, 630, 21, 31))
        self.label_37.setFont(font4)
        self.label_38 = QLabel(self.groupBox)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(170, 460, 21, 31))
        self.label_38.setFont(font4)
        self.label_39 = QLabel(self.groupBox)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(170, 290, 21, 31))
        self.label_39.setFont(font4)
        self.label_40 = QLabel(self.groupBox)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(170, 200, 21, 31))
        self.label_40.setFont(font4)
        self.label_41 = QLabel(self.groupBox)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(250, 170, 21, 31))
        self.label_41.setFont(font4)
        self.label_42 = QLabel(self.groupBox)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(420, 170, 21, 31))
        self.label_42.setFont(font4)
        self.label_43 = QLabel(self.groupBox)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(510, 170, 21, 31))
        self.label_43.setFont(font4)
        self.label_44 = QLabel(self.groupBox)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(680, 170, 21, 31))
        self.label_44.setFont(font4)
        self.label_45 = QLabel(self.groupBox)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(770, 170, 21, 31))
        self.label_45.setFont(font4)
        self.label_46 = QLabel(self.groupBox)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(940, 170, 21, 31))
        self.label_46.setFont(font4)
        self.label_47 = QLabel(self.groupBox)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(600, 170, 21, 31))
        self.label_47.setFont(font4)
        self.label_48 = QLabel(self.groupBox)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(850, 170, 21, 31))
        self.label_48.setFont(font4)
        self.label_49 = QLabel(self.groupBox)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(970, 250, 21, 31))
        self.label_49.setFont(font4)
        self.label_50 = QLabel(self.groupBox)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(970, 340, 21, 31))
        self.label_50.setFont(font4)
        self.label_51 = QLabel(self.groupBox)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(970, 510, 21, 31))
        self.label_51.setFont(font4)
        self.label_52 = QLabel(self.groupBox)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(970, 600, 21, 31))
        self.label_52.setFont(font4)
        self.label_53 = QLabel(self.groupBox)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(970, 770, 21, 31))
        self.label_53.setFont(font4)
        self.label_54 = QLabel(self.groupBox)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(970, 940, 21, 31))
        self.label_54.setFont(font4)
        self.label_55 = QLabel(self.groupBox)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(170, 800, 21, 31))
        self.label_55.setFont(font4)
        self.label_56 = QLabel(self.groupBox)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(170, 540, 21, 31))
        self.label_56.setFont(font4)

        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)


        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.verticalSpacer_2 = QSpacerItem(20, 75, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.currentPlayerLabel = QLabel(Dialog)
        self.currentPlayerLabel.setObjectName(u"currentPlayerLabel")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.currentPlayerLabel.sizePolicy().hasHeightForWidth())
        self.currentPlayerLabel.setSizePolicy(sizePolicy1)
        font5 = QFont()
        font5.setPointSize(24)
        font5.setBold(False)
        self.currentPlayerLabel.setFont(font5)
        self.currentPlayerLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.currentPlayerLabel)

        self.verticalSpacer = QSpacerItem(20, 75, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.playerInfoBox = QGroupBox(Dialog)
        self.playerInfoBox.setObjectName(u"playerInfoBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.playerInfoBox.sizePolicy().hasHeightForWidth())
        self.playerInfoBox.setSizePolicy(sizePolicy2)
        font6 = QFont()
        font6.setPointSize(20)
        self.playerInfoBox.setFont(font6)
        self.verticalLayout = QVBoxLayout(self.playerInfoBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.player1NameLabel = QLabel(self.playerInfoBox)
        self.player1NameLabel.setObjectName(u"player1NameLabel")
        palette28 = QPalette()
        brush2 = QBrush(QColor(170, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette28.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette28.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette28.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        self.player1NameLabel.setPalette(palette28)
        font7 = QFont()
        font7.setStrikeOut(False)
        self.player1NameLabel.setFont(font7)
        self.player1NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player1NameLabel)

        self.player1BalanceLabel = QLabel(self.playerInfoBox)
        self.player1BalanceLabel.setObjectName(u"player1BalanceLabel")
        self.player1BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player1BalanceLabel)

        self.player2NameLabel = QLabel(self.playerInfoBox)
        self.player2NameLabel.setObjectName(u"player2NameLabel")
        palette29 = QPalette()
        brush3 = QBrush(QColor(0, 170, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette29.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette29.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette29.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player2NameLabel.setPalette(palette29)
        self.player2NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player2NameLabel)

        self.player2BalanceLabel = QLabel(self.playerInfoBox)
        self.player2BalanceLabel.setObjectName(u"player2BalanceLabel")
        self.player2BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player2BalanceLabel)

        self.player3NameLabel = QLabel(self.playerInfoBox)
        self.player3NameLabel.setObjectName(u"player3NameLabel")
        palette30 = QPalette()
        brush4 = QBrush(QColor(0, 0, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette30.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette30.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette30.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player3NameLabel.setPalette(palette30)
        self.player3NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player3NameLabel)

        self.player3BalanceLabel = QLabel(self.playerInfoBox)
        self.player3BalanceLabel.setObjectName(u"player3BalanceLabel")
        self.player3BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player3BalanceLabel)

        self.player4NameLabel = QLabel(self.playerInfoBox)
        self.player4NameLabel.setObjectName(u"player4NameLabel")
        palette31 = QPalette()
        brush5 = QBrush(QColor(255, 170, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette31.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette31.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette31.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player4NameLabel.setPalette(palette31)
        self.player4NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player4NameLabel)

        self.player4BalanceLabel = QLabel(self.playerInfoBox)
        self.player4BalanceLabel.setObjectName(u"player4BalanceLabel")
        self.player4BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player4BalanceLabel)

        self.player5NameLabel = QLabel(self.playerInfoBox)
        self.player5NameLabel.setObjectName(u"player5NameLabel")
        palette32 = QPalette()
        brush6 = QBrush(QColor(85, 170, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette32.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette32.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette32.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player5NameLabel.setPalette(palette32)
        self.player5NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player5NameLabel)

        self.player5BalanceLabel = QLabel(self.playerInfoBox)
        self.player5BalanceLabel.setObjectName(u"player5BalanceLabel")
        self.player5BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player5BalanceLabel)

        self.player6NameLabel = QLabel(self.playerInfoBox)
        self.player6NameLabel.setObjectName(u"player6NameLabel")
        palette33 = QPalette()
        brush7 = QBrush(QColor(85, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette33.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette33.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette33.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player6NameLabel.setPalette(palette33)
        self.player6NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player6NameLabel)

        self.player6BalanceLabel = QLabel(self.playerInfoBox)
        self.player6BalanceLabel.setObjectName(u"player6BalanceLabel")
        self.player6BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player6BalanceLabel)

        self.player7NameLabel = QLabel(self.playerInfoBox)
        self.player7NameLabel.setObjectName(u"player7NameLabel")
        palette34 = QPalette()
        brush8 = QBrush(QColor(170, 85, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette34.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette34.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette34.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.player7NameLabel.setPalette(palette34)
        self.player7NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player7NameLabel)

        self.player7BalanceLabel = QLabel(self.playerInfoBox)
        self.player7BalanceLabel.setObjectName(u"player7BalanceLabel")
        self.player7BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player7BalanceLabel)

        self.player8NameLabel = QLabel(self.playerInfoBox)
        self.player8NameLabel.setObjectName(u"player8NameLabel")
        self.player8NameLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player8NameLabel)

        self.player8BalanceLabel = QLabel(self.playerInfoBox)
        self.player8BalanceLabel.setObjectName(u"player8BalanceLabel")
        self.player8BalanceLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.player8BalanceLabel)


        self.verticalLayout_2.addWidget(self.playerInfoBox)

        self.verticalSpacer_3 = QSpacerItem(20, 110, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer_3)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_7)

        self.tradeButton = QPushButton(Dialog)
        self.tradeButton.setObjectName(u"tradeButton")
        self.tradeButton.setMinimumSize(QSize(125, 75))
        self.tradeButton.setFont(font6)

        self.horizontalLayout.addWidget(self.tradeButton)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.mortgageButton = QPushButton(Dialog)
        self.mortgageButton.setObjectName(u"mortgageButton")
        self.mortgageButton.setMinimumSize(QSize(175, 75))
        self.mortgageButton.setFont(font6)

        self.horizontalLayout.addWidget(self.mortgageButton)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.housesButton = QPushButton(Dialog)
        self.housesButton.setObjectName(u"housesButton")
        self.housesButton.setMinimumSize(QSize(150, 75))
        self.housesButton.setFont(font6)

        self.horizontalLayout.addWidget(self.housesButton)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.transactionLabel = QLabel(Dialog)
        self.transactionLabel.setObjectName(u"transactionLabel")
        self.transactionLabel.setMinimumSize(QSize(670, 0))
        self.transactionLabel.setAlignment(Qt.AlignCenter)
        self.transactionLabel.setWordWrap(True)

        self.horizontalLayout.addWidget(self.transactionLabel)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_5)


        self.verticalLayout_3.addLayout(self.horizontalLayout)


        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox.setTitle("")
        self.boardImageLabel.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><img src=\":/newPrefix/gameBoard.png\"/></p></body></html>", None))
        self.endTurnButton.setText(QCoreApplication.translate("Dialog", u"End Turn", None))
        self.bankruptButton.setText(QCoreApplication.translate("Dialog", u"Bankrupt", None))
        self.displayLabel.setText(QCoreApplication.translate("Dialog", u"Display Message Here", None))
        self.dice1Outline.setText("")
        self.dice2Outline.setText("")
        self.dice1dot1.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot4.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot6.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot7.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot2.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot5.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice1dot3.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot5.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot3.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot7.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot6.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot1.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot2.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.dice2dot4.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"\u2022", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_36.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_41.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_43.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_45.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_46.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_47.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_51.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.currentPlayerLabel.setText(QCoreApplication.translate("Dialog", u"player1", None))
        self.playerInfoBox.setTitle(QCoreApplication.translate("Dialog", u"Players", None))
        self.player1NameLabel.setText(QCoreApplication.translate("Dialog", u"player1", None))
        self.player1BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player2NameLabel.setText(QCoreApplication.translate("Dialog", u"player2", None))
        self.player2BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player3NameLabel.setText(QCoreApplication.translate("Dialog", u"player3", None))
        self.player3BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player4NameLabel.setText(QCoreApplication.translate("Dialog", u"player4", None))
        self.player4BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player5NameLabel.setText(QCoreApplication.translate("Dialog", u"player5", None))
        self.player5BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player6NameLabel.setText(QCoreApplication.translate("Dialog", u"player6", None))
        self.player6BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player7NameLabel.setText(QCoreApplication.translate("Dialog", u"player7", None))
        self.player7BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.player8NameLabel.setText(QCoreApplication.translate("Dialog", u"player8", None))
        self.player8BalanceLabel.setText(QCoreApplication.translate("Dialog", u"\u00a30", None))
        self.tradeButton.setText(QCoreApplication.translate("Dialog", u"Trade", None))
        self.mortgageButton.setText(QCoreApplication.translate("Dialog", u"Mortgage", None))
        self.housesButton.setText(QCoreApplication.translate("Dialog", u"Houses", None))
        self.transactionLabel.setText(QCoreApplication.translate("Dialog", u"Transaction Message Here", None))
    # retranslateUi

